version: '3'
services:
  mongo:
    container_name: ecommerce-mongo
    image: mongo
    ports:
      - 27017:27017
    volumes:
      - mongodb_data_container:/data/db

  redis:
    container_name: ecommerce-redis
    image: redis
    ports:
      - 6379:6379

  zookeeper:
    image: 'bitnami/zookeeper:latest'
    environment:
      - ALLOW_ANONYMOUS_LOGIN=yes
    networks:
      - kafka-network

  kafka:
    container_name: ecommerce-kafka
    image: bitnami/kafka:latest
    ports:
      - 9092:9092
    environment:
      - KAFKA_BROKER_ID=1
      - KAFKA_ZOOKEEPER_CONNECT=zookeeper:2181
      - ALLOW_PLAINTEXT_LISTENER=yes
      - KAFKA_ADVERTISED_LISTENERS=PLAINTEXT://kafka:9092
      - KAFKA_LISTENERS=PLAINTEXT://:9092
      - KAFKA_ZOOKEEPER_PROTOCOL=PLAINTEXT
    networks:
      - kafka-network

  rabbitmq:
    container_name: ecommerce-rabbitmq
    image: rabbitmq:3-management
    ports:
      - 5672:5672
      - 15672:15672

networks:
  kafka-network:
    driver: bridge

volumes:
  mongodb_data_container:
