version: '3'
services:
  mongo:
    container_name: ecommerce-mongo
    image: mongo
    ports:
      - 27017:27017
    volumes:
      - mongodb_data_container:/data/db

  redis:
    container_name: ecommerce-redis
    image: redis
    ports:
      - 6379:6379

volumes:
  mongodb_data_container:
